name: Generate documentation
on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  generate_documentation:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore SpacemanDMM cache
        uses: actions/cache@v4
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm-${{ secrets.CACHE_PURGE_KEY }}
      - name: Install SpacemanDMM
        run: bash tools/ci/install_spaceman_dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
          touch dmdoc/.nojekyll
          echo codedocs.shiptest.net > dmdoc/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload output directory
          path: "dmdoc/"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
